
package ru.girfanov.tm.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-16T19:03:20.058+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "WrongSessionException", targetNamespace = "http://endpoint.tm.girfanov.ru/")
public class WrongSessionException_Exception extends Exception {

    private ru.girfanov.tm.endpoint.WrongSessionException wrongSessionException;

    public WrongSessionException_Exception() {
        super();
    }

    public WrongSessionException_Exception(String message) {
        super(message);
    }

    public WrongSessionException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public WrongSessionException_Exception(String message, ru.girfanov.tm.endpoint.WrongSessionException wrongSessionException) {
        super(message);
        this.wrongSessionException = wrongSessionException;
    }

    public WrongSessionException_Exception(String message, ru.girfanov.tm.endpoint.WrongSessionException wrongSessionException, java.lang.Throwable cause) {
        super(message, cause);
        this.wrongSessionException = wrongSessionException;
    }

    public ru.girfanov.tm.endpoint.WrongSessionException getFaultInfo() {
        return this.wrongSessionException;
    }
}
