package ru.girfanov.tmserver.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-08T12:00:33.714+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tmserver.girfanov.ru/", name = "DataDomainEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface DataDomainEndPoint {

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/getDataByFasterInXmlRequest", output = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/getDataByFasterInXmlResponse")
    @RequestWrapper(localName = "getDataByFasterInXml", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.GetDataByFasterInXml")
    @ResponseWrapper(localName = "getDataByFasterInXmlResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.GetDataByFasterInXmlResponse")
    public void getDataByFasterInXml(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/getDataBySerializationRequest", output = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/getDataBySerializationResponse")
    @RequestWrapper(localName = "getDataBySerialization", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.GetDataBySerialization")
    @ResponseWrapper(localName = "getDataBySerializationResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.GetDataBySerializationResponse")
    public void getDataBySerialization(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/saveDataByJaxbInJsonRequest", output = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/saveDataByJaxbInJsonResponse")
    @RequestWrapper(localName = "saveDataByJaxbInJson", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.SaveDataByJaxbInJson")
    @ResponseWrapper(localName = "saveDataByJaxbInJsonResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.SaveDataByJaxbInJsonResponse")
    public void saveDataByJaxbInJson(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/getDataByFasterInJsonRequest", output = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/getDataByFasterInJsonResponse")
    @RequestWrapper(localName = "getDataByFasterInJson", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.GetDataByFasterInJson")
    @ResponseWrapper(localName = "getDataByFasterInJsonResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.GetDataByFasterInJsonResponse")
    public void getDataByFasterInJson(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/saveDataByFasterInXmlRequest", output = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/saveDataByFasterInXmlResponse")
    @RequestWrapper(localName = "saveDataByFasterInXml", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.SaveDataByFasterInXml")
    @ResponseWrapper(localName = "saveDataByFasterInXmlResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.SaveDataByFasterInXmlResponse")
    public void saveDataByFasterInXml(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/saveDataBySerializationRequest", output = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/saveDataBySerializationResponse")
    @RequestWrapper(localName = "saveDataBySerialization", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.SaveDataBySerialization")
    @ResponseWrapper(localName = "saveDataBySerializationResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.SaveDataBySerializationResponse")
    public void saveDataBySerialization(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/getDataByJaxbInJsonRequest", output = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/getDataByJaxbInJsonResponse")
    @RequestWrapper(localName = "getDataByJaxbInJson", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.GetDataByJaxbInJson")
    @ResponseWrapper(localName = "getDataByJaxbInJsonResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.GetDataByJaxbInJsonResponse")
    public void getDataByJaxbInJson(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/getDataByJaxbInXmlRequest", output = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/getDataByJaxbInXmlResponse")
    @RequestWrapper(localName = "getDataByJaxbInXml", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.GetDataByJaxbInXml")
    @ResponseWrapper(localName = "getDataByJaxbInXmlResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.GetDataByJaxbInXmlResponse")
    public void getDataByJaxbInXml(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/saveDataByJaxbInXmlRequest", output = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/saveDataByJaxbInXmlResponse")
    @RequestWrapper(localName = "saveDataByJaxbInXml", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.SaveDataByJaxbInXml")
    @ResponseWrapper(localName = "saveDataByJaxbInXmlResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.SaveDataByJaxbInXmlResponse")
    public void saveDataByJaxbInXml(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/saveDataByFasterInJsonRequest", output = "http://endpoint.tmserver.girfanov.ru/DataDomainEndPoint/saveDataByFasterInJsonResponse")
    @RequestWrapper(localName = "saveDataByFasterInJson", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.SaveDataByFasterInJson")
    @ResponseWrapper(localName = "saveDataByFasterInJsonResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.SaveDataByFasterInJsonResponse")
    public void saveDataByFasterInJson(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session
    );
}
