package ru.girfanov.tmserver.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-08T12:31:22.583+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tmserver.girfanov.ru/", name = "TaskEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface TaskEndPoint {

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/removeAllTasksRequest", output = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/removeAllTasksResponse")
    @RequestWrapper(localName = "removeAllTasks", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.RemoveAllTasks")
    @ResponseWrapper(localName = "removeAllTasksResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.RemoveAllTasksResponse")
    public void removeAllTasks(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/findAllTasksRequest", output = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/findAllTasksResponse")
    @RequestWrapper(localName = "findAllTasks", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.FindAllTasks")
    @ResponseWrapper(localName = "findAllTasksResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.FindAllTasksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.girfanov.tmserver.endpoint.Task> findAllTasks(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/removeTaskRequest", output = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/removeTaskResponse")
    @RequestWrapper(localName = "removeTask", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.RemoveTask")
    @ResponseWrapper(localName = "removeTaskResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.RemoveTaskResponse")
    public void removeTask(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session,
        @WebParam(name = "taskUuid", targetNamespace = "")
        java.lang.String taskUuid
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/findOneTaskRequest", output = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/findOneTaskResponse")
    @RequestWrapper(localName = "findOneTask", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.FindOneTask")
    @ResponseWrapper(localName = "findOneTaskResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.FindOneTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.girfanov.tmserver.endpoint.Task findOneTask(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session,
        @WebParam(name = "taskUuid", targetNamespace = "")
        java.lang.String taskUuid
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/findAllTasksByProjectIdRequest", output = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/findAllTasksByProjectIdResponse")
    @RequestWrapper(localName = "findAllTasksByProjectId", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.FindAllTasksByProjectId")
    @ResponseWrapper(localName = "findAllTasksByProjectIdResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.FindAllTasksByProjectIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.girfanov.tmserver.endpoint.Task> findAllTasksByProjectId(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session,
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.String projectId
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/persistTaskRequest", output = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/persistTaskResponse")
    @RequestWrapper(localName = "persistTask", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.PersistTask")
    @ResponseWrapper(localName = "persistTaskResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.PersistTaskResponse")
    public void persistTask(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session,
        @WebParam(name = "task", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Task task
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/mergeTaskRequest", output = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/mergeTaskResponse")
    @RequestWrapper(localName = "mergeTask", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.MergeTask")
    @ResponseWrapper(localName = "mergeTaskResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.MergeTaskResponse")
    public void mergeTask(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session,
        @WebParam(name = "task", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Task task
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/removeAllTasksByProjectIdRequest", output = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/removeAllTasksByProjectIdResponse")
    @RequestWrapper(localName = "removeAllTasksByProjectId", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.RemoveAllTasksByProjectId")
    @ResponseWrapper(localName = "removeAllTasksByProjectIdResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.RemoveAllTasksByProjectIdResponse")
    public void removeAllTasksByProjectId(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session,
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.String projectId
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/findAllTasksSortedByValueRequest", output = "http://endpoint.tmserver.girfanov.ru/TaskEndPoint/findAllTasksSortedByValueResponse")
    @RequestWrapper(localName = "findAllTasksSortedByValue", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.FindAllTasksSortedByValue")
    @ResponseWrapper(localName = "findAllTasksSortedByValueResponse", targetNamespace = "http://endpoint.tmserver.girfanov.ru/", className = "ru.girfanov.tmserver.endpoint.FindAllTasksSortedByValueResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.girfanov.tmserver.endpoint.Task> findAllTasksSortedByValue(
        @WebParam(name = "session", targetNamespace = "")
        ru.girfanov.tmserver.endpoint.Session session,
        @WebParam(name = "value", targetNamespace = "")
        java.lang.String value
    );
}
